### ISSUE TITLE
Examples title doesn't fit in one line.

### ISSUE THREAD

**Issue by zbraniecki** [projectfluent/projectfluent.github.io#14]
![screenshot from 2017-10-12 08-55-32](https://user-images.githubusercontent.com/449986/31506074-452c2a00-af2b-11e7-8c84-2b18874ffb1e.png)

**Comment by stasm** [comment]
I don't see this on my machine regardless of the resolution. The font on your screenshot is pretty wide. I guess this is what happens when none of the fonts specified in the CSS are installed. Should we simply change the title to `Output`?

**Comment by zbraniecki** [comment]
yes pls! :)
