### ISSUE TITLE
projectfluent.io does not exists

### ISSUE THREAD

**Issue by galdiolo** [projectfluent/projectfluent.github.io#15]
Documentation refers to projectfluent.io (example http://projectfluent.io/play) but GitHub replies: "There isn't a GitHub Pages site here."

**Comment by stasm** [comment]
Thanks for reporting this! We had some issues with the .io domain and switched to http://projectfluent.org (https://github.com/projectfluent/fluent.js/pull/111). I thought I updated all links across all project pages but it looks like I forgot to deploy the changes in the Playground. I just pushed the updated version.

Please let me know if you still see references to `projectfluent.io` in other places!
