### ISSUE TITLE
Weird font formatting on firefox/linux 

### ISSUE THREAD

**Issue by jorisgio** [projectfluent/projectfluent.github.io#25]
Hello, i noticed the front pages renders very strangely on firefox 69 on linux. This is on a 4k screen, and the font selected is Liberation Sans 
![Screenshot_2019-06-20 Project Fluent](https://user-images.githubusercontent.com/1108145/59833449-a67bca80-9378-11e9-9e7a-a9bd0e435a34.png). I know basically nothing on web development, i'm not sure what additional information i can give.

**Comment by eemeli** [comment]
Closing as presumably stale.
